apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: tzsg8gc2f-go 
  janus-idp.io/tekton: tzsg8gc2f-go
  backstage.io/kubernetes-id: tzsg8gc2f-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tzsg8gc2f-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml